# Generated by Django 4.0.1 on 2022-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=60)),
                ('assignee', models.CharField(choices=[('ccaa', ' '), ('admin', ' '), ('charles', 'Charles Wang')], max_length=150)),
                ('bug', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('due_date', models.DateTimeField(verbose_name='date due')),
                ('resolved', models.BooleanField()),
            ],
        ),
    ]
