# Generated by Django 4.0.1 on 2022-01-23 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_issue_project_alter_issue_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 17, 19, 6, 920573, tzinfo=utc)),
        ),
    ]
