# Generated by Django 4.0.1 on 2022-02-02 02:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_project_description_alter_comment_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 2, 37, 46, 83827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 2, 37, 46, 82314, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.CharField(blank=True, max_length=500, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 2, 2, 2, 37, 46, 84775, tzinfo=utc))),
                ('assignee', models.ManyToManyField(blank=True, null=True, related_name='updatedassignee', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='core.issue')),
            ],
        ),
    ]
